# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "MarkupSafe" = super.buildPythonPackage rec {
    pname = "MarkupSafe";
    version = "2.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/95/7e/68018b70268fb4a2a605e2be44ab7b4dd7ce7808adae6c5ef32e34f4b55a/MarkupSafe-2.1.2.tar.gz";
      sha256 = "03a515mrh1l3cynrhcb5rjphmxkwdwd3hin7sii6s0r65f6brjmb";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "anyio" = super.buildPythonPackage rec {
    pname = "anyio";
    version = "3.6.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/77/2b/b4c0b7a3f3d61adb1a1e0b78f90a94e2b6162a043880704b7437ef297cad/anyio-3.6.2-py3-none-any.whl";
      sha256 = "1qsi382l4607lsjz8k8azhqlwa2h2824ap8wxprjwahd4yyk5gpv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."idna"
      self."sniffio"
    ];
  };
  "attrs" = super.buildPythonPackage rec {
    pname = "attrs";
    version = "22.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f2/bc/d817287d1aa01878af07c19505fafd1165cd6a119e9d0821ca1d1c20312d/attrs-22.1.0-py2.py3-none-any.whl";
      sha256 = "072mv8qgvas8sagx7f021l9yrca6ry3m8cqsylsdzwkvyq1a9vw6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "backoff" = super.buildPythonPackage rec {
    pname = "backoff";
    version = "2.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/df/73/b6e24bd22e6720ca8ee9a85a0c4a2971af8497d8f3193fa05390cbd46e09/backoff-2.2.1-py3-none-any.whl";
      sha256 = "1s4n0g5av9lrrbrsd5jybk30vqkcbdypsyz4yxw65q180sd9ymv3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2022.12.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/71/4c/3db2b8021bd6f2f0ceb0e088d6b2d49147671f25832fb17970e9b583d742/certifi-2022.12.7-py3-none-any.whl";
      sha256 = "065wqxligjai8la891i71s921q7xmpyc3krixhc6fvcjbqpj7lsa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "charset-normalizer" = super.buildPythonPackage rec {
    pname = "charset-normalizer";
    version = "2.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/db/51/a507c856293ab05cdc1db77ff4bc1268ddd39f29e7dc4919aa497f0adbec/charset_normalizer-2.1.1-py3-none-any.whl";
      sha256 = "17z2zvkvalb66i5hasshq0grsma8afs6hb1mi7yrl9qi35fsgsc3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "click" = super.buildPythonPackage rec {
    pname = "click";
    version = "8.1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c2/f1/df59e28c642d583f7dacffb1e0965d0e00b218e0186d7858ac5233dce840/click-8.1.3-py3-none-any.whl";
      sha256 = "0j6vn6ayxq1bqs1v64r90sarg05hj6rxj4w29vs0k9hmrcrq2kdv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "colorama" = super.buildPythonPackage rec {
    pname = "colorama";
    version = "0.4.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d1/d6/3965ed04c63042e047cb6a3e6ed1a63a35087b6a609aa3a15ed8ac56c221/colorama-0.4.6-py2.py3-none-any.whl";
      sha256 = "1ijz53xpmxds2qf02l9yf0rnp7bznwh3ci4xkw8wmh5cyn8rj7ag";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "curlify" = super.buildPythonPackage rec {
    pname = "curlify";
    version = "2.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fa/2c/9254b2294d0250291560d78e16e5cd764b8e2caa75d4cad1e8ae9d73899d/curlify-2.2.1.tar.gz";
      sha256 = "0vfxdmr1gqmfsny3hn1dccq6s6a5k13fyiggx0nrbbsz4gkh4gqd";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."requests"
    ];
  };
  "exceptiongroup" = super.buildPythonPackage rec {
    pname = "exceptiongroup";
    version = "1.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e8/14/9c6a7e5f12294ccd6975a45e02899ed25468cd7c2c86f3d9725f387f9f5f/exceptiongroup-1.1.0-py3-none-any.whl";
      sha256 = "07pc9dpm531932k6rlf40ak70dvvmf0pn45367h2svkmvaivsz1j";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "graphql-core" = super.buildPythonPackage rec {
    pname = "graphql-core";
    version = "3.2.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f8/39/e5143e7ec70939d2076c1165ae9d4a3815597019c4d797b7f959cf778600/graphql_core-3.2.3-py3-none-any.whl";
      sha256 = "1hrx60zgrfda9zp3mn6xd0w3wwcjvj3z52rz2fxchpmxa827hrjp";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "h11" = super.buildPythonPackage rec {
    pname = "h11";
    version = "0.14.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/95/04/ff642e65ad6b90db43e668d70ffb6736436c7ce41fcc549f4e9472234127/h11-0.14.0-py3-none-any.whl";
      sha256 = "0qd7z9p38dwx215048q708vd1sn2abdh1mb3hg66ii2ip324mzp3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "httpcore" = super.buildPythonPackage rec {
    pname = "httpcore";
    version = "0.16.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/04/7e/ef97af4623024e8159993b3114ce208de4f677098ae058ec5882a1bf7605/httpcore-0.16.3-py3-none-any.whl";
      sha256 = "1h4xjk1b57p1sxxphz146x8camkh66wgxr5xhjh8m4sag04bf7ys";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."anyio"
      self."certifi"
      self."h11"
      self."sniffio"
    ];
  };
  "httpx" = super.buildPythonPackage rec {
    pname = "httpx";
    version = "0.23.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ac/a2/0260c0f5d73bdf06e8d3fc1013a82b9f0633dc21750c9e3f3cb1dba7bb8c/httpx-0.23.3-py3-none-any.whl";
      sha256 = "1mhhwfrrkd3vl394gsal06jana9xkf3gjsndy0jflm0jkg7gq4d2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."httpcore"
      self."rfc3986"
      self."sniffio"
    ];
  };
  "hypothesis" = super.buildPythonPackage rec {
    pname = "hypothesis";
    version = "6.68.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/52/64/efbf22c4b7cf1452366b68d48fe0527bd3639c14ea7a570ed5fb14bf6dca/hypothesis-6.68.2-py3-none-any.whl";
      sha256 = "0kkxcr58h0vzrf343g67irz6377q98vlfig5jmc70lnydivcqh9a";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."exceptiongroup"
      self."sortedcontainers"
    ];
  };
  "hypothesis-graphql" = super.buildPythonPackage rec {
    pname = "hypothesis-graphql";
    version = "0.9.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/46/8a/bc99d332c4345228afc470624d43f079d1ecfc5c6f1894415aa9e12652c7/hypothesis_graphql-0.9.2-py3-none-any.whl";
      sha256 = "0j9frb030m90pvwki2b3w90z2mywxmicx2nvpc1fry1g0ydy919y";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."graphql-core"
      self."hypothesis"
    ];
  };
  "hypothesis-jsonschema" = super.buildPythonPackage rec {
    pname = "hypothesis-jsonschema";
    version = "0.22.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b6/3f/ffbaaa089b06c3b62ac3e09cfcc36981103416627bd1e37f626b33bead88/hypothesis_jsonschema-0.22.1-py3-none-any.whl";
      sha256 = "1rndabk5cdwfb3izrsxiaj0c057prd9qgc17jqvc5am6hv5nha88";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."hypothesis"
      self."jsonschema"
    ];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "3.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/34/3030de6f1370931b9dbb4dad48f6ab1015ab1d32447850b9fc94e60097be/idna-3.4-py3-none-any.whl";
      sha256 = "1hn54ps4kgv2fmyvfaks38sgrvjc1cn4834sh7gadsx3x9wpxdwh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "iniconfig" = super.buildPythonPackage rec {
    pname = "iniconfig";
    version = "2.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ef/a6/62565a6e1cf69e10f5727360368e451d4b7f58beeac6173dc9db836a5b46/iniconfig-2.0.0-py3-none-any.whl";
      sha256 = "0x43fyv1hpwpmvvqh73ldcyac9j2hb14mffis8i3nblxlxqmia5n";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jsonschema" = super.buildPythonPackage rec {
    pname = "jsonschema";
    version = "4.17.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c1/97/c698bd9350f307daad79dd740806e1a59becd693bd11443a0f531e3229b3/jsonschema-4.17.3-py3-none-any.whl";
      sha256 = "1xh8cnma4qj9g02g6yn5mh2zhrfj56n5r452ns2cma519ljssw58";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."pyrsistent"
    ];
  };
  "junit-xml" = super.buildPythonPackage rec {
    pname = "junit-xml";
    version = "1.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2a/93/2d896b5fd3d79b4cadd8882c06650e66d003f465c9d12c488d92853dff78/junit_xml-1.9-py2.py3-none-any.whl";
      sha256 = "0cj73dv2pmj89dm6hyd9dw8cfmnia59162yciz97dpggbajs2p7c";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "multidict" = super.buildPythonPackage rec {
    pname = "multidict";
    version = "6.0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4a/15/bd620f7a6eb9aa5112c4ef93e7031bcd071e0611763d8e17706ef8ba65e0/multidict-6.0.4.tar.gz";
      sha256 = "0jfsq7dnaja8jnd4ih02fhp6ic2ryhn7zfg7q19n9dzgj9j90rin";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "packaging" = super.buildPythonPackage rec {
    pname = "packaging";
    version = "23.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/35/a31aed2993e398f6b09a790a181a7927eb14610ee8bbf02dc14d31677f1c/packaging-23.0-py3-none-any.whl";
      sha256 = "1ch201bz087xfagzsy0hdyxz719bg9gq804vqacqrrn3jr2c2jki";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pluggy" = super.buildPythonPackage rec {
    pname = "pluggy";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/01/f38e2ff29715251cf25532b9082a1589ab7e4f571ced434f98d0139336dc/pluggy-1.0.0-py2.py3-none-any.whl";
      sha256 = "1lvvnc39v43v5jawq2wz0765rg9lkx8f25l4sqv1l0vz8nzln4vl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyrsistent" = super.buildPythonPackage rec {
    pname = "pyrsistent";
    version = "0.19.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/64/de/375aa14daaee107f987da76ca32f7a907fea00fa8b8afb67dc09bec0de91/pyrsistent-0.19.3-py3-none-any.whl";
      sha256 = "0r3bwr3mymr2fjpaxvgjh8cqkhyp9vwgs9hckwbi30cg42yxdw6c";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pytest" = super.buildPythonPackage rec {
    pname = "pytest";
    version = "7.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b2/68/5321b5793bd506961bd40bdbdd0674e7de4fb873ee7cab33dd27283ad513/pytest-7.2.2-py3-none-any.whl";
      sha256 = "0pi2wq73y9ppixpa1w3lz32rsq85y3ii4p67rsqw1ynwabsjh0qk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."exceptiongroup"
      self."iniconfig"
      self."packaging"
      self."pluggy"
      self."tomli"
    ];
  };
  "pytest-subtests" = super.buildPythonPackage rec {
    pname = "pytest-subtests";
    version = "0.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/47/ce/5860e0c84277f5b9c6f52ed7fb6f0b61bd460ef03cd32607a2eb2b385932/pytest_subtests-0.7.0-py3-none-any.whl";
      sha256 = "1bav15k1kznsf44r7lc8dd0g2bc7pwagvzvgx57lc37axp592dif";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pytest"
    ];
  };
  "pyyaml" = super.buildPythonPackage rec {
    pname = "pyyaml";
    version = "6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/36/2b/61d51a2c4f25ef062ae3f74576b01638bebad5e045f747ff12643df63844/PyYAML-6.0.tar.gz";
      sha256 = "18imkjacvpxfgg1lbpraqywx3j7hr5dv99d242byqvrh2jf53yv8";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "requests" = super.buildPythonPackage rec {
    pname = "requests";
    version = "2.28.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ca/91/6d9b8ccacd0412c08820f72cebaa4f0c0441b5cda699c90f618b6f8a1b42/requests-2.28.1-py3-none-any.whl";
      sha256 = "0jakwryf077k46wbs525hrkxlyg4prpq6hdc199ganrnl6hs5vwg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."charset-normalizer"
      self."idna"
      self."urllib3"
    ];
  };
  "rfc3986" = super.buildPythonPackage rec {
    pname = "rfc3986";
    version = "1.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c4/e5/63ca2c4edf4e00657584608bee1001302bbf8c5f569340b78304f2f446cb/rfc3986-1.5.0-py2.py3-none-any.whl";
      sha256 = "15raf577150bdnjqvr89n9xnc2cllw5dy4mh32r3ihhxbcgnwvd8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."idna"
    ];
  };
  "schemathesis" = super.buildPythonPackage rec {
    pname = "schemathesis";
    version = "3.18.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dc/89/0cb6cd22aff728ec5c5f4c55c128278eb34226a947a89a768adc6a985520/schemathesis-3.18.5-py3-none-any.whl";
      sha256 = "04pmb6gyhf1c0d7c8h2j8qh19js8bnvmsf8fi269hgrbqa0a08g2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."backoff"
      self."click"
      self."colorama"
      self."curlify"
      self."httpx"
      self."hypothesis"
      self."hypothesis-graphql"
      self."hypothesis-jsonschema"
      self."jsonschema"
      self."junit-xml"
      self."pytest"
      self."pytest-subtests"
      self."pyyaml"
      self."requests"
      self."starlette"
      self."starlette-testclient"
      self."tomli"
      self."tomli-w"
      self."typing-extensions"
      self."werkzeug"
      self."yarl"
    ];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.16.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl";
      sha256 = "0m02dsi8lvrjf4bi20ab6lm7rr6krz7pg6lzk3xjs2l9hqfjzfwa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sniffio" = super.buildPythonPackage rec {
    pname = "sniffio";
    version = "1.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c3/a0/5dba8ed157b0136607c7f2151db695885606968d1fae123dc3391e0cfdbf/sniffio-1.3.0-py3-none-any.whl";
      sha256 = "112k8azxisfcwpvx36rpgisxf15lxv0zgaza5snvggsv3v7gvkpf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sortedcontainers" = super.buildPythonPackage rec {
    pname = "sortedcontainers";
    version = "2.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/32/46/9cb0e58b2deb7f82b84065f37f3bffeb12413f947f9388e4cac22c4621ce/sortedcontainers-2.4.0-py2.py3-none-any.whl";
      sha256 = "1q3y4gdrb1d3595sxqlpk0j783hr8n9a6mz9hla0470gvspdqqx1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "starlette" = super.buildPythonPackage rec {
    pname = "starlette";
    version = "0.25.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b0/56/e7e16e133428ce19ff429d3d71aa7114048730385eea7d0985df5cf9aed6/starlette-0.25.0-py3-none-any.whl";
      sha256 = "0a46rcmbwp15yk0alp641b8pj6daq8wysggvnswr9m9zk3qiskvp";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."anyio"
      self."typing-extensions"
    ];
  };
  "starlette-testclient" = super.buildPythonPackage rec {
    pname = "starlette-testclient";
    version = "0.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/09/88/bfa945aa40a3b4a57eb692c0889eec935483d8693266d60d12a4975c3334/starlette_testclient-0.2.0-py3-none-any.whl";
      sha256 = "03njvq9hrm36vvq4qv95n0xplw1jj1w5qr46q2z5hb9h8sxcxg6z";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."requests"
      self."starlette"
    ];
  };
  "tomli" = super.buildPythonPackage rec {
    pname = "tomli";
    version = "2.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/97/75/10a9ebee3fd790d20926a90a2547f0bf78f371b2f13aa822c759680ca7b9/tomli-2.0.1-py3-none-any.whl";
      sha256 = "1k0fqfdylinb57s2aqwprahwbrsk3babg4gghz4g06hnlvky77ck";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tomli-w" = super.buildPythonPackage rec {
    pname = "tomli-w";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bb/01/1da9c66ecb20f31ed5aa5316a957e0b1a5e786a0d9689616ece4ceaf1321/tomli_w-1.0.0-py3-none-any.whl";
      sha256 = "0qs4byp2kx22inkj3n9gms8rj1h7d00nij9yafg7581hpvl0falz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "typing-extensions" = super.buildPythonPackage rec {
    pname = "typing-extensions";
    version = "4.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/31/25/5abcd82372d3d4a3932e1fa8c3dbf9efac10cc7c0d16e78467460571b404/typing_extensions-4.5.0-py3-none-any.whl";
      sha256 = "1d0ijp0h547p1zg34jpx03fyxcx8jg1fnc8ldp0qm6fx75f0hczv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "1.26.14";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fe/ca/466766e20b767ddb9b951202542310cba37ea5f2d792dae7589f1741af58/urllib3-1.26.14-py2.py3-none-any.whl";
      sha256 = "1qd7xh7ply92kyanm6nb5shymk9k77yckhx64iqi6nyqyz1cvvbm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "werkzeug" = super.buildPythonPackage rec {
    pname = "werkzeug";
    version = "2.2.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f6/f8/9da63c1617ae2a1dec2fbf6412f3a0cfe9d4ce029eccbda6e1e4258ca45f/Werkzeug-2.2.3-py3-none-any.whl";
      sha256 = "04m6bll525ryaifif8npc6n8jhvlbszg69660qrm64hzpihkjhsn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
  };
  "yarl" = super.buildPythonPackage rec {
    pname = "yarl";
    version = "1.8.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c4/1e/1b204050c601d5cd82b45d5c8f439cb6f744a2ce0c0a6f83be0ddf0dc7b2/yarl-1.8.2.tar.gz";
      sha256 = "0qhm1dwwd8wp3fwh88qrip23b19jymmvy0l6jz83l0g3qq139m29";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."idna"
      self."multidict"
    ];
  };
}
